language: go
install: true
sudo: required
go:
  - 1.x

env:
  global:
    - CC_TEST_REPORTER_ID=88795f8e4fefcdb16839fb681856e38e7dc631ebb43f9c10ea66f57ee4e29cf8

services:
  - docker

before_install:
  - docker pull shap/godev:latest

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./enter --ci

after_script:
  - ./cc-test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT
  