language: go
install: true
sudo: required
go:
  - 1.x

services:
  - docker

before_install:
  - docker pull krig/godev:latest

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./enter --ci

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  